# ───────────────────────────────────────────────
#  Default profile – what every plain `forge …`
#  command uses when you don’t pass --profile
# ───────────────────────────────────────────────
[profile.default]
src         = "src"
out         = "out"
libs        = ["lib"]
remappings  = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
via_ir      = true
optimizer_runs = 200        # ← new: slightly faster compile while iterating

# ───────────────────────────────────────────────
#  Coverage profile – invoked with:
#      forge coverage --profile cov
# ───────────────────────────────────────────────
[profile.cov]
src         = "src"
out         = "out"
libs        = ["lib"]
remappings  = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
via_ir      = true
optimizer_runs = 9999       # recommended for LCOV mapping accuracy
fs_permissions = [{ access = "read", path = "./" }]

# ───────────────────────────────────────────────
#  (Optional) Production‑deploy build profile
#  Run with: forge script … --profile prod
# ───────────────────────────────────────────────
[profile.prod]
src         = "src"
out         = "out"
libs        = ["lib"]
remappings  = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
via_ir      = true
optimizer_runs = 999999      # squeeze every last gas unit